config/routes.rb
Rails.application.routes.draw do

  root to:'homes#top'
  
  resources :lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_one_attached :image

    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id), notice: "投稿成功"
    else
      render :index
    end
  end
  
  def index
    @list = List.new
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list.id), notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end 

  private
  
  def list_params
    params.require(:list).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<%= link_to "一覧へ", lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_post.html.erb
<h1>新規投稿</h1>
<% if list.errors.any? %>
  <%= list.errors.count %> 件のエラーが発生しました
  <ul>
    <% list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: list, local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <%= f.submit '投稿' %>
<% end %>

app/views/lists/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @list do |f| %>

    <h4><タイトル/h4>
    <%= f.text_field :title %>
  
    <h4>本文</h4>
    <%= f.text_area :body %>
    
    <%= f.submit '保存' %>
    
  <% end %>

app/views/lists/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>New Post</h2>
      <%= render "post", list: @list %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>投稿一覧</h1>
      <% if @lists.present? %>
        <% @lists.each do |list| %>
          <p>タイトル</p>
          <span>
            <%= link_to list.title, list_path(list.id) %>
          </span>
          <p>画像</p>
          <% if list.image.attached? %>
            <%= image_tag list.image, size: "200x200" %>
          <% else %>
            <p>画像がありません。</p>
          <% end %>
        <% end %>
      <% else %>
        <p>投稿がありません。</p>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
     <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
     <% end %>
  </ul>

<%= form_with model: @list, url:lists_path, method: :post do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>本文</h4>
    <%= f.text_area :body %>

    <h4>画像</h4>
    <%= f.file_field :image, accept: "image/*" %>

    <%= f.submit '投稿' %>
<% end %>

app/views/lists/show.html.erb
<h1>タイトル</h1>
<p><%= @list.title %></p>

<h1>本文</h1>
<p><%= @list.body %></p>

<p>画像</p>
    <% if @list.image.attached? %>
     <%= image_tag @list.image, size: "200x200" %>
    <% else %>
     <p>画像がありません。</p>
    <% end %>

<%= link_to "編集", edit_list_path(@list.id) %>
<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>